import css from './styles.css';
import { mergePapers, SOURCES } from './sources.js';
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => s ? new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}) : '尚未核查';
const sourceLink = (s, label) => `<a href="${esc(SOURCES[s])}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;

export function render(data, origin) {
 const { school, scholar, crossref, news, sourceStatus, storageAvailable, initialSnapshot } = data;
 const papers = mergePapers(school,scholar,crossref);
 const grouped = new Map();
 for(const p of papers){const year=p.year||'年份待核对';if(!grouped.has(year))grouped.set(year,[]);grouped.get(year).push(p);}
 const latest = papers.filter(p => Number(p.year)>=2026).slice(0,3);
 const boldAuthor = authors => esc(authors).replace(/\b(Bo Ma|B\.? Ma)\b|马博/g,'<strong>$&</strong>');
 const intro = (school.intro?.[0] || '').replace(/，男，\d{4}年\d{1,2}月生/,'');
 const summary = `${intro} ${(school.intro || []).find(p=>/主要研究方向/.test(p)) || school.research}`;
 const sourceRows = ['school','scholar','crossref'].map(s=>{const status=sourceStatus[s];return `<div class="sourcerow"><div>${sourceLink(s,s==='school'?'学校个人主页':s==='scholar'?'Google Scholar':'出版社记录')}</div><div><p>${s==='school'?'简介、研究方向、项目与招生信息':s==='scholar'?'论文列表与引用指标':'通过论文绑定的 ORCID 匹配作者，补充出版记录和 DOI'}</p><p class="meta">数据核实：${date(status.updatedAt)}（北京时间）</p>${status.error?`<p class="sourceerror">本次访问未成功，保留已核实资料。</p>`:''}</div></div>`}).join('');
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>马博 Bo Ma · 浙江工商大学 · 个人科研主页</title><meta name="description" content="浙江工商大学信息与电子工程学院马博副教授的个人科研主页：低空与无人机网络、算力网络、强化学习，论文、项目与招生信息。"><link rel="canonical" href="${esc(origin)}/"><link rel="icon" href="./favicon.svg" type="image/svg+xml"><meta property="og:title" content="马博 Bo Ma · 个人科研主页"><meta property="og:description" content="浙江工商大学 · 低空与无人机网络 · 算力网络"><meta property="og:url" content="${esc(origin)}/"><meta name="theme-color" content="#172c45"><style>${css}</style></head><body>
 <a class="skip" href="#about">跳到主要内容</a><header><div class="nav"><a class="brand" href="./">马博 / Bo Ma <span>浙江工商大学</span></a><nav class="navlinks" aria-label="主要导航"><a href="#about">简介</a><a href="#news">动态</a><a href="#publications">论文</a><a href="#honors">新闻与荣誉</a><a href="#projects">项目</a><a href="#teaching">教学与招生</a><a href="#sources">信息来源</a></nav></div></header>
 <div class="layout"><aside class="identity" aria-label="个人资料"><img class="portrait" src="./portrait.png?v=26349bae" alt="马博" width="150" height="200"><h1>马博</h1><div class="englishname">Bo Ma</div><p class="role">${esc(school.role)}</p><p class="institution">浙江工商大学<br>信息与电子工程学院<br>School of Information and<br>Electronic Engineering</p><div class="contactlinks"><a class="contactlink" href="mailto:${esc(school.email)}">${esc(school.email)}</a>${sourceLink('school','学校主页')}${sourceLink('scholar','Google Scholar')}<a class="contactlink" href="https://www.researchgate.net/profile/Bo-Ma-43" target="_blank" rel="noopener noreferrer">ResearchGate</a>${sourceLink('crossref','ORCID')}<a class="contactlink" href="https://ieeexplore.ieee.org/author/37087239360" target="_blank" rel="noopener noreferrer">IEEE Xplore</a></div><div class="sidefoot">浙江省杭州市<br>下沙高教园区学正街18号<br>信电楼 403</div></aside>
 <main>${!storageAvailable?'<p class="warning">更新服务暂不可用，当前展示已核实的资料快照。</p>':''}
 <section id="about"><div class="eyebrow">Research profile</div><div class="sectionhead" style="margin-top:10px"><h2>个人简介</h2></div><p class="intro">${esc(summary)}</p><div class="researchgrid"><div class="researchitem"><h3>低空与无人机网络</h3><span class="en">Low-altitude & UAV networks</span></div><div class="researchitem"><h3>算力网络</h3><span class="en">Computing power networks</span></div><div class="researchitem"><h3>强化学习与网络优化</h3><span class="en">Reinforcement learning & network optimization</span></div></div><p class="meta">${sourceLink('school','个人信息来源：学校主页')}</p><div class="metrics"><div class="metric"><strong>${papers.length}</strong><span>已收录成果</span></div><div class="metric"><strong>${esc(scholar.metrics.citations)}</strong><span>Scholar 引用</span></div><div class="metric"><strong>${esc(scholar.metrics.hIndex)}</strong><span>h 指数</span></div></div><p class="meta" style="margin-top:10px">引用指标为 Google Scholar 快照 · ${date(sourceStatus.scholar.updatedAt)}（北京时间）</p><details><summary>教育经历与完整简介</summary><div class="detailcopy"><ul class="smalllist"><li>2017–2021 · 英国谢菲尔德大学 · 通信工程博士</li><li>2015–2016 · 英国纽卡斯尔大学 · 通信与信号处理硕士</li><li>2010–2014 · 东南大学 · 自动化学士</li></ul>${school.intro.filter(p=>!/电子邮箱|李传煌教授主页/.test(p)).map(p=>`<p>${esc(p)}</p>`).join('')}</div></details></section>
 <section id="news"><div class="sectionhead"><h2>近期科研动态</h2><span class="meta">按来源中的年份展示</span></div><div class="notices">${latest.map(p=>`<div class="notice"><span class="date">${esc(p.year)}</span><div><p><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.title)}</a></p><span class="meta">${esc(p.journal)}</span></div></div>`).join('')}<div class="notice"><span class="date">2025</span><p>主持国家自然科学基金青年项目「低时延高可靠无人机边缘算力网络」（2025–2027）。 ${sourceLink('school','来源')}</p></div></div></section>
 <section id="honors"><div class="sectionhead"><h2>新闻与荣誉</h2><span class="meta">${sourceLink('school','学校主页记录')}</span></div><div class="notices">${(news?.articles||[]).map(n=>`<div class="notice"><span class="date">${esc(n.date||'报道')}</span><div><p><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">${esc(n.title)}</a></p><span class="meta">${esc(n.excerpt)}</span></div></div>`).join('')}${school.awards.filter(p=>/2025年度|国家级金奖|历史建筑|恒安智卫|省级金奖/.test(p)).map(p=>`<div class="notice"><span class="date">2025</span><p>${esc(p)}</p></div>`).join('')}</div><div class="notice" style="margin-top:20px"><span class="date">任职</span><div><p>省派科技副总 · 国家互联网交换中心</p><span class="meta">任职信息由本人提供。</span></div></div><p class="meta" style="margin-top:20px">竞赛成果按学校主页中的团队项目与指导教师记录展示。报道链接收录后保留原文日期。</p></section>
 <section id="publications"><div class="sectionhead"><h2>研究论文</h2><span class="meta">${papers.length} 条 · 来源合并去重</span></div><p class="meta">包含期刊论文、会议论文与预印本；作者及发表信息以链接原文为准。</p>${[...grouped].map(([year,list])=>`<div class="yeargroup"><div class="yearlabel">${esc(year)}</div><div>${list.map(p=>`<article class="paper"><h3><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.title)}</a> ${/arxiv|preprint/i.test(p.journal)?'<span class="preprint">预印本</span>':''}</h3><div class="authors">${boldAuthor(p.authors)}</div><div class="journal">${esc(p.journal)}</div><div class="paperlinks"><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${p.source==='scholar'?'Scholar 记录':p.source==='crossref'?'DOI 原文':'学校成果记录'}</a>${p.doi?`<a href="https://doi.org/${esc(p.doi)}" target="_blank" rel="noopener noreferrer">DOI 原文</a>`:""}${p.sources.map(s=>sourceLink(s,s==='school'?'学校主页':s==='scholar'?'学者主页':'出版社记录')).join('')}${p.citations!=null?`<span class="meta">引用 ${esc(p.citations)}</span>`:''}</div></article>`).join('')}</div></div>`).join('')}</section>
 <section id="projects"><div class="sectionhead"><h2>科研项目</h2><span class="meta">${sourceLink('school','来源：学校主页')}</span></div>${school.projects.map((p,i)=>`<div class="project"><span class="projectnum">${String(i+1).padStart(2,'0')}</span><p>${esc(p.replace(/^\d+\s*[.．]\s*/,''))}</p></div>`).join('')}</section>
 <section id="teaching"><div class="sectionhead"><h2>教学与招生</h2></div><div class="split"><div><h3>本科教学</h3><p>${esc(school.teaching)}</p><h3 style="margin-top:25px">荣誉与育人成果</h3><ul class="smalllist">${school.awards.filter(p=>/2025年度|国家级金奖|省级金奖/.test(p)).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div><div><h3>科研合作与研究生指导</h3><p>${esc(school.recruitment)}</p><p><a href="mailto:${esc(school.email)}">通过学校邮箱联系</a></p><p class="meta">具体招生安排请以学院当年度通知为准。</p></div></div></section>
 <section id="sources"><div class="sectionhead"><h2>信息来源与更新</h2></div><div class="sourcebox">${sourceRows}<p class="meta" style="margin:16px 0 0">根据已确认的学校主页和 Scholar 学者档案整理。来源暂不可访问时，保留上次成功核实的内容。${initialSnapshot?' 当前为首次整理的数据快照。':''}</p></div></section>
 </main></div><footer><span>© ${new Date().getUTCFullYear()} 马博 · Bo Ma</span><span>浙江工商大学 · 杭州</span></footer></body></html>`;
}
